add log2 scale SH-56
VKCOM/statshouse pull request #1605
Opened 2024-12-04 14:29 UTC by VasiliyTrue

2024-12-04 16:02 UTC, vauweb commented on statshouse-ui/src/components2/Plot/PlotView/PlotViewMetric.tsx
> +    };
и почему  -1 и 1 это же не корректные значения получаются

2024-12-05 09:46 UTC, VasiliyTrue commented on statshouse-ui/src/components2/Plot/PlotView/PlotViewMetric.tsx
> +    };
Math.pow(2, 1024); // Infinity
Math.pow(2, -1024); // -Infinity
проверка на слишком большие значения. Да -1 и 1 неккоректно ставить вместо этого, уберу

2024-12-05 11:59 UTC, vauweb requested changes

2024-12-05 11:59 UTC, vauweb commented on statshouse-ui/src/common/helpers.ts
> +  if (num === 0 || incr === 0) return 0;
этого тут не было? зачем оно тут?

2024-12-05 11:59 UTC, vauweb commented on statshouse-ui/src/common/helpers.ts
> +      !singleIncr ? localIncrs.push(0) : localIncrs.push(singleIncr);
что будет когда сработает условие !singleIncr? 
будет incrRoundUp(num, 0) где произойдет (num / 0)? это корректно?

как и говорил инкрис не может быть равен 0

2024-12-05 11:59 UTC, vauweb commented on statshouse-ui/src/components2/Plot/PlotView/PlotViewMetric.tsx
> +                self: any,
без any там есть вполне нормальны тип uPlot

2024-12-05 11:59 UTC, vauweb commented on statshouse-ui/src/components2/Plot/PlotView/PlotViewMetric.tsx
> +                _axisIdx: number,
тут есть кой-то секретный смысл в префиксе _ ?

2024-12-05 12:10 UTC, VasiliyTrue commented on statshouse-ui/src/common/helpers.ts
> +  if (num === 0 || incr === 0) return 0;
`  const rawSplits = localSplits.map((v, i) => {
    const n = localIncrs[i];

    return incrRoundUp(self.posToVal(v, 'y'), n);
  });`
  
  здесь по коду туда отправляется 0 с Y кординаты, он вернет NaN, поэтому проверка на 0

2024-12-05 12:11 UTC, VasiliyTrue commented on statshouse-ui/src/components2/Plot/PlotView/PlotViewMetric.tsx
> +                _axisIdx: number,
нет, обычно так называют аргументы, которые не используются, eslint ругнулся

2024-12-05 12:58 UTC, VasiliyTrue commented on statshouse-ui/src/common/helpers.ts
> +      !singleIncr ? localIncrs.push(0) : localIncrs.push(singleIncr);
в некоторых кейсах singleIncr undefined или NaN, но итоговый результат получается корректный, как и с 0, поэтому лишнюю логику можно убрать, убрал

2024-12-06 07:56 UTC, vauweb submitted a review, later dismissed

2024-12-10 11:34 UTC, vauweb approved these changes

2024-12-10 12:22 UTC, merged