Add trusted subnet groups
VKCOM/statshouse pull request #25
Opened 2022-11-30 11:07 UTC by alpinskiy

2022-11-30 12:11 UTC, flyingmutant requested changes

2022-11-30 12:11 UTC, flyingmutant commented on internal/vkgo/build/version.go
> +	_ = json.Unmarshal([]byte(trustedSubnetGroups), &trustedSubnetGroupsS)
ошибка парсинга тут -- это серьезный мисконфиг, нельзя игнорировать (и в целом ошибки нельзя игнорировать)

2022-11-30 12:57 UTC, alpinskiy commented on internal/vkgo/build/version.go
> +	_ = json.Unmarshal([]byte(trustedSubnetGroups), &trustedSubnetGroupsS)
трейс в STDERR или exit(1) ?

2022-11-30 13:38 UTC, flyingmutant approved these changes

2022-11-30 16:45 UTC, flyingmutant approved these changes

2022-12-01 09:20 UTC, nevgeny approved these changes

2022-12-01 09:21 UTC, merged