Sync HTTP & RPC API
VKCOM/statshouse pull request #589
Opened 2023-06-22 16:17 UTC by alpinskiy

2023-06-22 16:18 UTC, vauweb approved these changes

2023-06-23 07:56 UTC, nevgeny requested changes

2023-06-23 07:56 UTC, nevgeny commented on internal/data_model/api.tl
> +    name: string
сломает текущие клиенты

2023-06-23 07:56 UTC, nevgeny commented on internal/data_model/api.tl
> +    widthAgg: string
сломает текущие клиенты

2023-06-27 19:11 UTC, nevgeny commented on internal/data_model/api.tl
> +    widthAgg: fields_mask.3?string
Давай point запросы не будем трогать. Там все уже хорошо, я потом выпилю все ненужное

2023-06-27 19:15 UTC, nevgeny commented on internal/data_model/api.tl
> +    name: query_fields_mask.4?%string
`%` в raw типах, кажется, не нужен

2023-06-28 11:38 UTC, nevgeny approved these changes

2023-06-28 13:23 UTC, merged