[sh-api] add select duration methods
VKCOM/statshouse pull request #92
Opened 2022-12-19 20:34 UTC by nevgeny

2022-12-19 20:51 UTC, flyingmutant commented on internal/api/handler.go
> +	ChSelectMetricDuration(duration, metric, table, string(kind), isFast)
может стоит писать с тегом status (хотя бы `ok`/`error` для начала), чтобы мы видели метрику и в случае успеха и в случае ошибок?

не очень удобно работать с метрикой, которая иногда пишется, а иногда -- нет

2022-12-20 10:54 UTC, flyingmutant commented on internal/format/builtin.go
> +					Raw:         true,
IsMetric:    true,

2022-12-20 10:55 UTC, flyingmutant commented on internal/format/builtin.go
> +					Raw:         true,
IsMetric: true

2022-12-22 11:27 UTC, flyingmutant requested changes
так а где `IsMetric: true`?

2022-12-26 19:15 UTC, flyingmutant approved these changes

2022-12-27 00:14 UTC, hrissan approved these changes

2022-12-27 08:37 UTC, merged