New tag name (numbers only) handler
VKCOM/statshouse pull request #94
Opened 2022-12-20 11:56 UTC by alpinskiy

fixes OG image renderer

2022-12-20 12:13 UTC, flyingmutant commented on internal/api/httputil.go
> +		return "key" + tagID, nil
format.TagID / format.NewTagID etc. -- не надо хардкодить константы, чтобы потом через find usages можно было легко найти

2022-12-22 11:31 UTC, flyingmutant requested changes
уже есть `func TagID(i int) string` / `func NewTagID(i int) string` -- кажется что ничего не нужно делать публичным

2022-12-22 13:59 UTC, alpinskiy commented
> уже есть `func TagID(i int) string` / `func NewTagID(i int) string` -- кажется что ничего не нужно делать публичным

убрал

2022-12-22 19:17 UTC, flyingmutant commented on internal/api/httputil.go
> +	if i, err := strconv.Atoi(tagID); err == nil && 0 <= i && i < format.MaxTags {
отписал в чате :-)

2022-12-22 19:41 UTC, flyingmutant approved these changes

2022-12-22 19:47 UTC, merged