fix: inconsistent reading from metadata
VKCOM/statshouse pull request #95
Opened 2022-12-21 15:27 UTC by nevgeny

2022-12-22 11:23 UTC, flyingmutant commented on internal/metadata/dbv2.go
> +	err := db.eng.Do(context.Background(), func(conn sqlite2.Conn, cache []byte) ([]byte, error) {
мы не должны указывать здесь контекст -- мы должны пробросить его, и только на верхнем уровне указать `context.Background()`

2022-12-22 11:23 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +	replica            = iota
лучше явно чиселки прописывать, `iota` очень редко используется и есть всякие подводные камни того как она работает

2022-12-22 11:23 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +				log.Panicf("binlog.Start() failed: %v", err)
почему паника, если у нас метод который возвращает ошибку? кажется что раньше было лучше

2022-12-22 11:23 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +		c := e.start(context.Background(), false)
точно не можем лучше чем `context.Background()`?

2022-12-22 11:23 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +	c := e.start(context.Background(), false)
`context.Background()` в 100 местах в коде -- выглядит не супер

2022-12-22 11:23 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +		if err := r.ctx.Err(); err != nil {
почему не проверяем `Done`? какая-то странная семантика

2022-12-22 11:23 UTC, flyingmutant commented on internal/vkgo/sqlite/engine_test.go
> +}
зачем коммитим такое? если тест не нужно гонять -- должен быть `t.Skip("explanation")` в начале, и все

2022-12-26 10:06 UTC, nevgeny commented on internal/vkgo/sqlite/engine.go
> +		if err := r.ctx.Err(); err != nil {
If Done is not yet closed, Err returns nil.
If Done is closed, Err returns a non-nil error explaining why

2022-12-26 10:45 UTC, nevgeny commented on internal/vkgo/sqlite/engine.go
> +	replica            = iota
В моем случае ок, я не завязываюсь на значения только на сами константы

2022-12-26 10:57 UTC, nevgeny commented on internal/vkgo/sqlite/engine.go
> +				log.Panicf("binlog.Start() failed: %v", err)
Паника тут необходима, так как Start может завершиться ошибкой уже после выхода из внешнего метода Open. После того как упал бинлог, сервис не может работать корректно

2022-12-26 12:32 UTC, nevgeny commented on internal/vkgo/sqlite/engine.go
> +	c := e.start(context.Background(), false)
В случае с созданием снэпшотов лимит сделать не получится, так как все зависит от размера базы. В остальных случаях сделал с таймаутом, там где это возможно

2022-12-26 19:28 UTC, flyingmutant requested changes
второй коммит -- отдельным мр-ом, пожалуйста

2022-12-26 19:31 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +				log.Panicf("binlog.Start() failed: %v", err)
звучит крайне опасно, и скорее всего приведет просто к падению приложения

2022-12-26 19:33 UTC, flyingmutant commented on internal/vkgo/sqlite/engine.go
> +		}()
`defer close(engineStarted)`?

2022-12-27 11:53 UTC, nevgeny commented on internal/vkgo/sqlite/engine.go
> +				log.Panicf("binlog.Start() failed: %v", err)
Это ок что упадет. Лучше чем будет пытаться как-то менять стейт и все запросы фейлить. Особенно в режиме когда мы не ждем коммитов, будет отвечать всем ок, хотя на самом деле данные не попали в бинлог

2022-12-27 15:28 UTC, flyingmutant commented
- sqlite engine -- wait for WaitBinlogPos, handle SetReturnBinlogPos
- ` e.opt.DurabilityMode == WaitCommit && e.mode == replica`?
- 1s + 3s timers
- no panic!
- top-level `context.Background()`
- `bytebufferpool`

2022-12-28 08:10 UTC, nevgeny commented
Оставил паники в горутине биолога так как там пока нет способа остановить(сообщить о нарушении инварианта) во время коммита или скипа

2022-12-28 14:12 UTC, flyingmutant approved these changes

2022-12-28 14:12 UTC, merged